name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "maxymasan.dev@gmail.com"
          git config --global user.name "maxyma-sanx"

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Deploy
        run: npm run deploy
